### ISSUE TITLE
Is this repository actively supported and developed?

### ISSUE THREAD

**Issue by m0canu1** [Forcepoint/fp-NGFW-SMC-ansible#4]
Hi,

I started to use this module for Ansible to do some repetitive tasks and did them with success and ease.

I wanted to know if this repository is still under development because I see that the latest update was made 2 years ago.

Also, I found this on Ansible Galaxy 
[https://galaxy.ansible.com/ui/repo/published/fp_flexedge_secure_sdwan/flexedge_secure_sdwan_ansible/](https://galaxy.ansible.com/ui/repo/published/fp_flexedge_secure_sdwan/flexedge_secure_sdwan_ansible/)

and wanted to know if it's related to Forcepoint or if it's made by someome who needed to install this module via Ansible Galaxy.

Thank you.

**Comment by amol-suruse** [comment]
Hello

Recently, we have released new developments as part of this repository with a new tag (1.0.1). And we are going to release new developments in this repo in the future. So I recommend using this repo for your task. 

Thank You.

**Comment by m0canu1** [comment]
Are you planning to also release it in the Ansible Galaxy?

**Comment by amol-suruse** [comment]
We don't have any plans yet. so better use this repo.
